version: "3.8"

services:
  db:
    image: mysql:8
    container_name: bugtracker-mysql
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: buguser
      MYSQL_PASSWORD: bugpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bugtracker-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bugtracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: buguser
      SPRING_DATASOURCE_PASSWORD: bugpass
    ports:
      - "8080:8080"
